const PREVIEW_MIN_LENGTH = 10;
const IMAGE_MIN_COUNT = 6;
const IMAGE_MAX_COUNT = 6;
const TITLE_MIN_LENGTH = 10;
const TITLE_MAX_LENGTH = 100;
const DESCRIPTION_MIN_LENGTH = 20;
const DESCRIPTION_MAX_LENGTH = 1024;
const COMMENT_MIN_LENGTH = 5;
const COMMENT_MAX_LENGTH = 1024;
const PASSWORD_MIN_LENGTH = 6;
const PASSWORD_MAX_LENGTH = 12;
const RATING_MIN = 1;
const RATING_MAX = 5;
const ROOMS_MIN = 1;
const ROOMS_MAX = 8;
const ADULTS_MIN = 1;
const ADULTS_MAX = 10;
const PRICE_MIN = 100;
const PRICE_MAX = 100000;
const LATITUDE_MIN = 48.85661;
const LATITUDE_MAX = 53.550341;
const LONGITUDE_MIN = 2.351499;
const LONGITUDE_MAX = 10.000654;

export {
  PREVIEW_MIN_LENGTH,
  IMAGE_MIN_COUNT,
  IMAGE_MAX_COUNT,
  TITLE_MIN_LENGTH,
  TITLE_MAX_LENGTH,
  DESCRIPTION_MIN_LENGTH,
  DESCRIPTION_MAX_LENGTH,
  COMMENT_MIN_LENGTH,
  COMMENT_MAX_LENGTH,
  PASSWORD_MIN_LENGTH,
  PASSWORD_MAX_LENGTH,
  RATING_MIN,
  RATING_MAX,
  ROOMS_MIN,
  ROOMS_MAX,
  ADULTS_MIN,
  ADULTS_MAX,
  PRICE_MIN,
  PRICE_MAX,
  LATITUDE_MIN,
  LATITUDE_MAX,
  LONGITUDE_MIN,
  LONGITUDE_MAX
};
